# **ДЗ к уроку 6**

**Задание 1.**


Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

**Решение.**

1. Используем формулу определения ковариации:
$$cov = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)$$

Подставляем значения в формулу, получим cov = 9157.84;

2. Используем формулу определения коэффициента кореляции Пирсона:
$$cor = cov / (np.std(zp) * np.std(ks))$$

Подставляем значения в формулу, получим cor = 0.8875.


In [72]:
import numpy as np
import pandas as pd

In [73]:
zp = pd.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110], float)
ks = pd.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832], float)

# Количество измерений zp
zp_n = zp.size

# Среднее арифметическое zp
zp_mean = zp.sum() / zp_n
print(zp_mean)

# Несмещенная оценка дисперсии zp
zp_var_ddof_1 = ((zp - zp_mean)**2).sum() / (zp_n - 1)
print(zp_var_ddof_1)

# Среднеквадратическое отклонение выборки zp
zp_std_ddof_1 = np.sqrt(((zp - zp_mean)**2).sum() / (zp_n - 1))
print(zp_std_ddof_1)

# Количество измерений ks
ks_n = zp.size

# Среднее арифметическое ks
ks_mean = ks.sum() / ks_n
print(ks_mean)

# Несмещенная оценка дисперсии ks
ks_var_ddof_1 = ((ks - ks_mean)**2).sum() / (ks_n - 1)
print(ks_var_ddof_1)

# Среднеквадратическое отклонение выборки sk
ks_std_ddof_1 = np.sqrt(((ks - ks_mean)**2).sum() / (ks_n - 1))
print(ks_std_ddof_1)

# Проверка
print('Количество измерений zp:\t\t\t', zp_n)
print('Количество измерений ks:\t\t\t', ks_n)
print('Сумма значений zp:\t\t\t\t', zp.sum())
print('Сумма значений ks:\t\t\t\t', ks.sum())
print('Среднее значений zp:\t\t\t\t', zp.mean())
print('Среднее значений ks:\t\t\t\t', ks.mean())
print('Несмещенная дисперсия zp:\t\t\t', zp.var(ddof=1))
print('Несмещенная дисперсия ks:\t\t\t', ks.var(ddof=1))
print('Несмещенное среднеквадратичное отклонение zp:\t', zp.std(ddof=1))
print('Несмещенное среднеквадратичное отклонение ks:\t', ks.std(ddof=1))


101.4
3882.9333333333334
62.31318747531162
709.9
33854.32222222223
183.99544076477068
Количество измерений zp:			 10
Количество измерений ks:			 10
Сумма значений zp:				 1014.0
Сумма значений ks:				 7099.0
Среднее значений zp:				 101.4
Среднее значений ks:				 709.9
Несмещенная дисперсия zp:			 3882.9333333333334
Несмещенная дисперсия ks:			 33854.32222222223
Несмещенное среднеквадратичное отклонение zp:	 62.31318747531162
Несмещенное среднеквадратичное отклонение ks:	 183.99544076477068


In [74]:
# Ковариация
cov = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
print("Ковариация расчетная:\t\t\t\t", cov)

print("Проверка расчета ковариации")
# Проверка расчета ковариации
print("numpy (ddof=0):\n", np.cov(zp, ks, ddof=0))

# Проверка расчета ковариации (ddof=1 - по умолчанию)
print("numpy (ddof=1):\n", np.cov(zp, ks, ddof=1))

# Проверка расчета ковариации (pandas)
# К сожалению, в методе pandas.Series().cov() нет параметра, аналогичного ddof,
# поэтому значение ковариации получается как при ddof=1
print("pandas:\n", pd.Series(zp).cov(pd.Series(ks)))

print("-----------------------------")

# Проверка расчета ковариации
cor = cov / (np.std(zp) * np.std(ks))
print("Коэффициент корреляции Пирсона расчетный:\t", cor)

print("Проверка расчета коэффициента кореляции")
# Проверка расчета к. кореляции
print("numpy:\n", np.corrcoef(zp, ks))

# Проверка расчета к. кореляции (pandas)
print("pandas:\n", pd.Series(zp).corr(pd.Series(ks)))


Ковариация расчетная:				 9157.839999999997
Проверка расчета ковариации
numpy (ddof=0):
 [[ 3494.64  9157.84]
 [ 9157.84 30468.89]]
numpy (ddof=1):
 [[ 3882.93333333 10175.37777778]
 [10175.37777778 33854.32222222]]
pandas:
 10175.377777777776
-----------------------------
Коэффициент корреляции Пирсона расчетный:	 0.8874900920739158
Проверка расчета коэффициента кореляции
numpy:
 [[1.         0.88749009]
 [0.88749009 1.        ]]
pandas:
 0.8874900920739162


**Задание 2.**


Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

**Решение.**

Среднее арифметическое:
M(X) = Σ(I = 1, n) xi / n = 118.1

Несмещенная дисперсия:
D(X) = Σ(I = 1, n) (xi - X)**2 / (n – 1) = 111.2(1)

Несмещенное среднеквадратичное отклонение:
σ = D(X)**0.5 = 10.5456

Используем формулу определения доверительного интервала при неизвестной  генеральной совокупности: $$\bar{X}\ \ \pm\ t_{{\alpha}/{2}}\ \ast\ {\sigma}/{\sqrt n}$$
Подставляем значения в формулу при p = 1 - α => α = 0.05; t(α/2 = 0.025, v = n - 1 = 9) = 2.262:
$$118.1 \pm 2.262 * 10.5456 / \sqrt{10} = [110.556; 125.644]\ при\ α=5\%$$

In [75]:
input_data = pd.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111], float)
n = input_data.size
print('Количество измерений:\t\t\t\t', n)
print('Сумма значений:\t\t\t\t\t', input_data.sum())
print('Среднее значений:\t\t\t\t', input_data.mean())
print('Несмещенная дисперсия:\t\t\t\t', input_data.var(ddof=1))
print('Несмещенное среднеквадратичное отклонение:\t', input_data.std(ddof=1))

# Среднее арифметическое
mean = input_data.sum() / n
print(mean)

# Несмещенная оценка дисперсии
var_ddof_1 = ((input_data - mean)**2).sum() / (n - 1)
print(var_ddof_1)

# Среднеквадратическое отклонение выборки
std_ddof_1 = np.sqrt(((input_data - mean)**2).sum() / (n - 1))
print(std_ddof_1)


Количество измерений:				 10
Сумма значений:					 1181.0
Среднее значений:				 118.1
Несмещенная дисперсия:				 111.21111111111111
Несмещенное среднеквадратичное отклонение:	 10.54566788359614
118.1
111.21111111111111
10.54566788359614


In [76]:
import scipy.stats
import math

p = 0.95
a = 1 - p
x1 = scipy.stats.t.ppf(a / 2, n - 1)
x2 = scipy.stats.t.ppf(1 - a / 2, n - 1)
print(x1)
print(x2)

-2.2621571627409915
2.2621571627409915


In [77]:
x1 = mean + x1 * std_ddof_1 / math.sqrt(n)
x1

110.55608365158724

In [78]:
x2 = mean + x2 * std_ddof_1 / math.sqrt(n)
x2

125.64391634841274

**Задание 3.**

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.


**Решение.**

Используем формулу определения доверительного интервала при известной  генеральной совокупности: $$\bar{X}\ \ \pm\ Z_{{\alpha}/{2}}\ \ast\ {\sigma}/{\sqrt n}$$
Подставляем значения в формулу при p = 1 - α => α = 0.05; Z(α/2 = 1 - 0.025) = 1.96:
$$174.2 \pm 1.96 * {\sqrt{25 / 27}} = [172.314; 176.086]\ при\ α=5\%$$

In [79]:
from scipy.stats import norm


mean = 174.2
var = 25
n = 27
p = 0.95


a = 1 - p
x1 = norm.ppf(a / 2)
x1

-1.959963984540054

In [80]:
x2 = norm.ppf(1 - a / 2)
x2

1.959963984540054

In [81]:
# Проверка
print(norm.cdf(x1))
print(norm.cdf(x2))


0.025
0.975


In [82]:
x1 = mean + x1 * math.sqrt(var / n)
x1

172.3140237765397

In [83]:
x2 = mean + x2 * math.sqrt(var / n)
x2

176.08597622346028

**Задание 4.**

Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики
и напишите ее в комментарии к Практическому заданию. (ПРОЕКТ ДОБРОВОЛЬНЫЙ)

Описание курсового проекта по предмету Теория вероятностей и математическая статистика

Во второй половине курса студентам даётся проект с темой на выбор. Студентам предлагается общее направление для проекта - исследовать данные с imdb. Для этих данных можно сделать EDA (Exploratory Data Analysis – разведочный анализ данных) либо проверить предложенную самим студентом статистическую гипотезу. При наличии опыта работы с данными и статистикой некоторые студенты также могут взять другую тему - например, исследовать курс биткойна.

В качестве данных студенты могут брать датасеты с информацией с сайта imdb (либо с Kaggle, либо откуда-то из Интернета, эти данные нужно искать самим). Также есть возможность взять любые другие данные, если выбрана другая тема. Работы выполняются с использованием любых методов из вебинаров и методичек по предмету Теория вероятностей и математическая статистика. Это может быть постановка и проверка статистических гипотез, EDA, дисперсионный анализ и т.д.

Готовый проект должен быть выложен на github в аккаунте студента в виде файла с расширением ipynb (Jupyter Notebook), ссылка на проект прикладывается в раздел Задание. Срок выполнения задания - неделя после 8-го вебинара. Начинать можно после 6-го вебинара, после того, как преподаватель одобрит тему (студент указывает тему работы в Задание к вебинару 6).

Ссылка на проект должна быть добавлена студентом к Заданию вебинара 8.

Примеры постановки темы проекта:

Проверить гипотезу: Комедийные фильмы, снятые до 1990 года, в среднем имеют более высокую оценку, чем комедийные фильмы, снятые позже.
Статистическое сопоставление цены биткоина с курсами фиатных активов (USD,EUR,RUR), ценами на нефть, драг металлы или с ценами других криптовалют по отношению к биткойну.
Также студент может до выполнения работы поставить широкий круг задач для проекта и уже в процессе выполнения оставить только то, что вошло в проект.

Пример:

"В проектной работе хотела бы сделать анализ по Странам по данным imbd.com.
По странам рассчитать основные статистические показатели: Мода, медиана, квартили, дисперсию.
Проверить, работает ли нормальное распределение и Паретто.
Проверить есть ли зависимость бюджетов, рейтингов, жанров от страны выпуска фильмов.
Посмотреть поведение стран во времени.
В идеале, хотела бы сделать прогноз на 2020 год: какие страны с какой вероятностью выпустят определенное количество фильмов с определенным бюджетом определенного жанра."

**Ответ.**

Конечно, же я буду делать проектную работу по курсу "Теории вероятностей и математической статистики".

С темой, пожалуй, я уже определился. Тут ничего нового для текущей ситуации - я, как и многие, хочу, чтобы в этой работе был хоть какой-то практический смысл. Данные по COVID-19 я уже нашел на github, а вот что, какие именно данные и как их анализировать я пока еще не созрел, слишком мало знаний. Я думаю, после 7-го или 8-го урока станет яснее.